# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scoreBase.ui'
#
# Created: Mon Jun 22 17:51:32 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_scoreBase(object):
    def setupUi(self, scoreBase):
        scoreBase.setObjectName(_fromUtf8("scoreBase"))
        scoreBase.resize(641, 339)
        self.verticalLayout = QtGui.QVBoxLayout(scoreBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.baseName = QtGui.QLabel(scoreBase)
        self.baseName.setMaximumSize(QtCore.QSize(16777215, 53))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.baseName.setFont(font)
        self.baseName.setText(_fromUtf8(""))
        self.baseName.setTextFormat(QtCore.Qt.RichText)
        self.baseName.setAlignment(QtCore.Qt.AlignCenter)
        self.baseName.setWordWrap(True)
        self.baseName.setObjectName(_fromUtf8("baseName"))
        self.verticalLayout.addWidget(self.baseName)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(scoreBase)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.name1 = QtGui.QComboBox(scoreBase)
        self.name1.setObjectName(_fromUtf8("name1"))
        self.horizontalLayout.addWidget(self.name1)
        self.label_2 = QtGui.QLabel(scoreBase)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.points1 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points1.sizePolicy().hasHeightForWidth())
        self.points1.setSizePolicy(sizePolicy)
        self.points1.setMaximumSize(QtCore.QSize(43, 16777215))
        self.points1.setObjectName(_fromUtf8("points1"))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.points1)
        self.label_3 = QtGui.QLabel(scoreBase)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.comments1 = QtGui.QLineEdit(scoreBase)
        self.comments1.setObjectName(_fromUtf8("comments1"))
        self.horizontalLayout.addWidget(self.comments1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(scoreBase)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.name2 = QtGui.QComboBox(scoreBase)
        self.name2.setObjectName(_fromUtf8("name2"))
        self.horizontalLayout_3.addWidget(self.name2)
        self.label_5 = QtGui.QLabel(scoreBase)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.points2 = QtGui.QComboBox(scoreBase)
        self.points2.setObjectName(_fromUtf8("points2"))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.points2)
        self.label_6 = QtGui.QLabel(scoreBase)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comments2 = QtGui.QLineEdit(scoreBase)
        self.comments2.setObjectName(_fromUtf8("comments2"))
        self.horizontalLayout_3.addWidget(self.comments2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(scoreBase)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.name3 = QtGui.QComboBox(scoreBase)
        self.name3.setObjectName(_fromUtf8("name3"))
        self.horizontalLayout_4.addWidget(self.name3)
        self.label_8 = QtGui.QLabel(scoreBase)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.points3 = QtGui.QComboBox(scoreBase)
        self.points3.setObjectName(_fromUtf8("points3"))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.points3)
        self.label_9 = QtGui.QLabel(scoreBase)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.comments3 = QtGui.QLineEdit(scoreBase)
        self.comments3.setObjectName(_fromUtf8("comments3"))
        self.horizontalLayout_4.addWidget(self.comments3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_10 = QtGui.QLabel(scoreBase)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.name4 = QtGui.QComboBox(scoreBase)
        self.name4.setObjectName(_fromUtf8("name4"))
        self.horizontalLayout_5.addWidget(self.name4)
        self.label_11 = QtGui.QLabel(scoreBase)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.points4 = QtGui.QComboBox(scoreBase)
        self.points4.setObjectName(_fromUtf8("points4"))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.points4)
        self.label_12 = QtGui.QLabel(scoreBase)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.comments4 = QtGui.QLineEdit(scoreBase)
        self.comments4.setObjectName(_fromUtf8("comments4"))
        self.horizontalLayout_5.addWidget(self.comments4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonBox = QtGui.QDialogButtonBox(scoreBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(scoreBase)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), scoreBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), scoreBase.reject)
        QtCore.QMetaObject.connectSlotsByName(scoreBase)

    def retranslateUi(self, scoreBase):
        scoreBase.setWindowTitle(_translate("scoreBase", "Score Base", None))
        self.label.setText(_translate("scoreBase", "Name", None))
        self.label_2.setText(_translate("scoreBase", "Points", None))
        self.points1.setItemText(0, _translate("scoreBase", "0", None))
        self.points1.setItemText(1, _translate("scoreBase", "1", None))
        self.points1.setItemText(2, _translate("scoreBase", "2", None))
        self.points1.setItemText(3, _translate("scoreBase", "3", None))
        self.points1.setItemText(4, _translate("scoreBase", "4", None))
        self.points1.setItemText(5, _translate("scoreBase", "5", None))
        self.points1.setItemText(6, _translate("scoreBase", "6", None))
        self.points1.setItemText(7, _translate("scoreBase", "7", None))
        self.points1.setItemText(8, _translate("scoreBase", "8", None))
        self.points1.setItemText(9, _translate("scoreBase", "9", None))
        self.points1.setItemText(10, _translate("scoreBase", "10", None))
        self.points1.setItemText(11, _translate("scoreBase", "11", None))
        self.points1.setItemText(12, _translate("scoreBase", "12", None))
        self.points1.setItemText(13, _translate("scoreBase", "13", None))
        self.points1.setItemText(14, _translate("scoreBase", "14", None))
        self.points1.setItemText(15, _translate("scoreBase", "15", None))
        self.label_3.setText(_translate("scoreBase", "Comments", None))
        self.label_4.setText(_translate("scoreBase", "Name", None))
        self.label_5.setText(_translate("scoreBase", "Points", None))
        self.points2.setItemText(0, _translate("scoreBase", "0", None))
        self.points2.setItemText(1, _translate("scoreBase", "1", None))
        self.points2.setItemText(2, _translate("scoreBase", "2", None))
        self.points2.setItemText(3, _translate("scoreBase", "3", None))
        self.points2.setItemText(4, _translate("scoreBase", "4", None))
        self.points2.setItemText(5, _translate("scoreBase", "5", None))
        self.points2.setItemText(6, _translate("scoreBase", "6", None))
        self.points2.setItemText(7, _translate("scoreBase", "7", None))
        self.points2.setItemText(8, _translate("scoreBase", "8", None))
        self.points2.setItemText(9, _translate("scoreBase", "9", None))
        self.points2.setItemText(10, _translate("scoreBase", "10", None))
        self.points2.setItemText(11, _translate("scoreBase", "11", None))
        self.points2.setItemText(12, _translate("scoreBase", "12", None))
        self.points2.setItemText(13, _translate("scoreBase", "13", None))
        self.points2.setItemText(14, _translate("scoreBase", "14", None))
        self.points2.setItemText(15, _translate("scoreBase", "15", None))
        self.label_6.setText(_translate("scoreBase", "Comments", None))
        self.label_7.setText(_translate("scoreBase", "Name", None))
        self.label_8.setText(_translate("scoreBase", "Points", None))
        self.points3.setItemText(0, _translate("scoreBase", "0", None))
        self.points3.setItemText(1, _translate("scoreBase", "1", None))
        self.points3.setItemText(2, _translate("scoreBase", "2", None))
        self.points3.setItemText(3, _translate("scoreBase", "3", None))
        self.points3.setItemText(4, _translate("scoreBase", "4", None))
        self.points3.setItemText(5, _translate("scoreBase", "5", None))
        self.points3.setItemText(6, _translate("scoreBase", "6", None))
        self.points3.setItemText(7, _translate("scoreBase", "7", None))
        self.points3.setItemText(8, _translate("scoreBase", "8", None))
        self.points3.setItemText(9, _translate("scoreBase", "9", None))
        self.points3.setItemText(10, _translate("scoreBase", "10", None))
        self.points3.setItemText(11, _translate("scoreBase", "11", None))
        self.points3.setItemText(12, _translate("scoreBase", "12", None))
        self.points3.setItemText(13, _translate("scoreBase", "13", None))
        self.points3.setItemText(14, _translate("scoreBase", "14", None))
        self.points3.setItemText(15, _translate("scoreBase", "15", None))
        self.label_9.setText(_translate("scoreBase", "Comments", None))
        self.label_10.setText(_translate("scoreBase", "Name", None))
        self.label_11.setText(_translate("scoreBase", "Points", None))
        self.points4.setItemText(0, _translate("scoreBase", "0", None))
        self.points4.setItemText(1, _translate("scoreBase", "1", None))
        self.points4.setItemText(2, _translate("scoreBase", "2", None))
        self.points4.setItemText(3, _translate("scoreBase", "3", None))
        self.points4.setItemText(4, _translate("scoreBase", "4", None))
        self.points4.setItemText(5, _translate("scoreBase", "5", None))
        self.points4.setItemText(6, _translate("scoreBase", "6", None))
        self.points4.setItemText(7, _translate("scoreBase", "7", None))
        self.points4.setItemText(8, _translate("scoreBase", "8", None))
        self.points4.setItemText(9, _translate("scoreBase", "9", None))
        self.points4.setItemText(10, _translate("scoreBase", "10", None))
        self.points4.setItemText(11, _translate("scoreBase", "11", None))
        self.points4.setItemText(12, _translate("scoreBase", "12", None))
        self.points4.setItemText(13, _translate("scoreBase", "13", None))
        self.points4.setItemText(14, _translate("scoreBase", "14", None))
        self.points4.setItemText(15, _translate("scoreBase", "15", None))
        self.label_12.setText(_translate("scoreBase", "Comments", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    scoreBase = QtGui.QDialog()
    ui = Ui_scoreBase()
    ui.setupUi(scoreBase)
    scoreBase.show()
    sys.exit(app.exec_())

