# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scoreBase.ui'
#
# Created: Mon Jun 29 15:15:25 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_scoreBase(object):
    def setupUi(self, scoreBase):
        scoreBase.setObjectName(_fromUtf8("scoreBase"))
        scoreBase.resize(641, 211)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(scoreBase.sizePolicy().hasHeightForWidth())
        scoreBase.setSizePolicy(sizePolicy)
        scoreBase.setMaximumSize(QtCore.QSize(641, 211))
        self.gridLayout_2 = QtGui.QGridLayout(scoreBase)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.baseName = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseName.sizePolicy().hasHeightForWidth())
        self.baseName.setSizePolicy(sizePolicy)
        self.baseName.setMaximumSize(QtCore.QSize(621, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.baseName.setFont(font)
        self.baseName.setText(_fromUtf8(""))
        self.baseName.setTextFormat(QtCore.Qt.RichText)
        self.baseName.setAlignment(QtCore.Qt.AlignCenter)
        self.baseName.setWordWrap(True)
        self.baseName.setObjectName(_fromUtf8("baseName"))
        self.verticalLayout.addWidget(self.baseName)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(38, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name1 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name1.sizePolicy().hasHeightForWidth())
        self.name1.setSizePolicy(sizePolicy)
        self.name1.setMaximumSize(QtCore.QSize(78, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name1.setFont(font)
        self.name1.setObjectName(_fromUtf8("name1"))
        self.gridLayout.addWidget(self.name1, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.points1 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points1.sizePolicy().hasHeightForWidth())
        self.points1.setSizePolicy(sizePolicy)
        self.points1.setMaximumSize(QtCore.QSize(43, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.points1.setFont(font)
        self.points1.setObjectName(_fromUtf8("points1"))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.points1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.points1, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(72, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.comments1 = QtGui.QLineEdit(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments1.sizePolicy().hasHeightForWidth())
        self.comments1.setSizePolicy(sizePolicy)
        self.comments1.setMaximumSize(QtCore.QSize(316, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comments1.setFont(font)
        self.comments1.setObjectName(_fromUtf8("comments1"))
        self.gridLayout.addWidget(self.comments1, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(38, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.name2 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name2.sizePolicy().hasHeightForWidth())
        self.name2.setSizePolicy(sizePolicy)
        self.name2.setMaximumSize(QtCore.QSize(78, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name2.setFont(font)
        self.name2.setObjectName(_fromUtf8("name2"))
        self.gridLayout.addWidget(self.name2, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.points2 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points2.sizePolicy().hasHeightForWidth())
        self.points2.setSizePolicy(sizePolicy)
        self.points2.setMaximumSize(QtCore.QSize(45, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.points2.setFont(font)
        self.points2.setObjectName(_fromUtf8("points2"))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.points2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.points2, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(72, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.comments2 = QtGui.QLineEdit(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments2.sizePolicy().hasHeightForWidth())
        self.comments2.setSizePolicy(sizePolicy)
        self.comments2.setMaximumSize(QtCore.QSize(316, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comments2.setFont(font)
        self.comments2.setObjectName(_fromUtf8("comments2"))
        self.gridLayout.addWidget(self.comments2, 1, 5, 1, 1)
        self.label_7 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(38, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.name3 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name3.sizePolicy().hasHeightForWidth())
        self.name3.setSizePolicy(sizePolicy)
        self.name3.setMaximumSize(QtCore.QSize(78, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name3.setFont(font)
        self.name3.setObjectName(_fromUtf8("name3"))
        self.gridLayout.addWidget(self.name3, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.points3 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points3.sizePolicy().hasHeightForWidth())
        self.points3.setSizePolicy(sizePolicy)
        self.points3.setMaximumSize(QtCore.QSize(45, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.points3.setFont(font)
        self.points3.setObjectName(_fromUtf8("points3"))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.points3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.points3, 2, 3, 1, 1)
        self.label_9 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(72, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1)
        self.comments3 = QtGui.QLineEdit(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments3.sizePolicy().hasHeightForWidth())
        self.comments3.setSizePolicy(sizePolicy)
        self.comments3.setMaximumSize(QtCore.QSize(316, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comments3.setFont(font)
        self.comments3.setObjectName(_fromUtf8("comments3"))
        self.gridLayout.addWidget(self.comments3, 2, 5, 1, 1)
        self.label_10 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(38, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.name4 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name4.sizePolicy().hasHeightForWidth())
        self.name4.setSizePolicy(sizePolicy)
        self.name4.setMaximumSize(QtCore.QSize(78, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name4.setFont(font)
        self.name4.setObjectName(_fromUtf8("name4"))
        self.gridLayout.addWidget(self.name4, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(40, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.points4 = QtGui.QComboBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points4.sizePolicy().hasHeightForWidth())
        self.points4.setSizePolicy(sizePolicy)
        self.points4.setMaximumSize(QtCore.QSize(45, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.points4.setFont(font)
        self.points4.setObjectName(_fromUtf8("points4"))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.points4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.points4, 3, 3, 1, 1)
        self.label_12 = QtGui.QLabel(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(72, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 4, 1, 1)
        self.comments4 = QtGui.QLineEdit(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments4.sizePolicy().hasHeightForWidth())
        self.comments4.setSizePolicy(sizePolicy)
        self.comments4.setMaximumSize(QtCore.QSize(316, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comments4.setFont(font)
        self.comments4.setObjectName(_fromUtf8("comments4"))
        self.gridLayout.addWidget(self.comments4, 3, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtGui.QDialogButtonBox(scoreBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMaximumSize(QtCore.QSize(621, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(scoreBase)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), scoreBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), scoreBase.reject)
        QtCore.QMetaObject.connectSlotsByName(scoreBase)

    def retranslateUi(self, scoreBase):
        scoreBase.setWindowTitle(_translate("scoreBase", "Score Base", None))
        self.label.setText(_translate("scoreBase", "Name", None))
        self.label_2.setText(_translate("scoreBase", "Points", None))
        self.points1.setItemText(0, _translate("scoreBase", "0", None))
        self.points1.setItemText(1, _translate("scoreBase", "1", None))
        self.points1.setItemText(2, _translate("scoreBase", "2", None))
        self.points1.setItemText(3, _translate("scoreBase", "3", None))
        self.points1.setItemText(4, _translate("scoreBase", "4", None))
        self.points1.setItemText(5, _translate("scoreBase", "5", None))
        self.points1.setItemText(6, _translate("scoreBase", "6", None))
        self.points1.setItemText(7, _translate("scoreBase", "7", None))
        self.points1.setItemText(8, _translate("scoreBase", "8", None))
        self.points1.setItemText(9, _translate("scoreBase", "9", None))
        self.points1.setItemText(10, _translate("scoreBase", "10", None))
        self.points1.setItemText(11, _translate("scoreBase", "11", None))
        self.points1.setItemText(12, _translate("scoreBase", "12", None))
        self.points1.setItemText(13, _translate("scoreBase", "13", None))
        self.points1.setItemText(14, _translate("scoreBase", "14", None))
        self.points1.setItemText(15, _translate("scoreBase", "15", None))
        self.label_3.setText(_translate("scoreBase", "Comments", None))
        self.label_4.setText(_translate("scoreBase", "Name", None))
        self.label_5.setText(_translate("scoreBase", "Points", None))
        self.points2.setItemText(0, _translate("scoreBase", "0", None))
        self.points2.setItemText(1, _translate("scoreBase", "1", None))
        self.points2.setItemText(2, _translate("scoreBase", "2", None))
        self.points2.setItemText(3, _translate("scoreBase", "3", None))
        self.points2.setItemText(4, _translate("scoreBase", "4", None))
        self.points2.setItemText(5, _translate("scoreBase", "5", None))
        self.points2.setItemText(6, _translate("scoreBase", "6", None))
        self.points2.setItemText(7, _translate("scoreBase", "7", None))
        self.points2.setItemText(8, _translate("scoreBase", "8", None))
        self.points2.setItemText(9, _translate("scoreBase", "9", None))
        self.points2.setItemText(10, _translate("scoreBase", "10", None))
        self.points2.setItemText(11, _translate("scoreBase", "11", None))
        self.points2.setItemText(12, _translate("scoreBase", "12", None))
        self.points2.setItemText(13, _translate("scoreBase", "13", None))
        self.points2.setItemText(14, _translate("scoreBase", "14", None))
        self.points2.setItemText(15, _translate("scoreBase", "15", None))
        self.label_6.setText(_translate("scoreBase", "Comments", None))
        self.label_7.setText(_translate("scoreBase", "Name", None))
        self.label_8.setText(_translate("scoreBase", "Points", None))
        self.points3.setItemText(0, _translate("scoreBase", "0", None))
        self.points3.setItemText(1, _translate("scoreBase", "1", None))
        self.points3.setItemText(2, _translate("scoreBase", "2", None))
        self.points3.setItemText(3, _translate("scoreBase", "3", None))
        self.points3.setItemText(4, _translate("scoreBase", "4", None))
        self.points3.setItemText(5, _translate("scoreBase", "5", None))
        self.points3.setItemText(6, _translate("scoreBase", "6", None))
        self.points3.setItemText(7, _translate("scoreBase", "7", None))
        self.points3.setItemText(8, _translate("scoreBase", "8", None))
        self.points3.setItemText(9, _translate("scoreBase", "9", None))
        self.points3.setItemText(10, _translate("scoreBase", "10", None))
        self.points3.setItemText(11, _translate("scoreBase", "11", None))
        self.points3.setItemText(12, _translate("scoreBase", "12", None))
        self.points3.setItemText(13, _translate("scoreBase", "13", None))
        self.points3.setItemText(14, _translate("scoreBase", "14", None))
        self.points3.setItemText(15, _translate("scoreBase", "15", None))
        self.label_9.setText(_translate("scoreBase", "Comments", None))
        self.label_10.setText(_translate("scoreBase", "Name", None))
        self.label_11.setText(_translate("scoreBase", "Points", None))
        self.points4.setItemText(0, _translate("scoreBase", "0", None))
        self.points4.setItemText(1, _translate("scoreBase", "1", None))
        self.points4.setItemText(2, _translate("scoreBase", "2", None))
        self.points4.setItemText(3, _translate("scoreBase", "3", None))
        self.points4.setItemText(4, _translate("scoreBase", "4", None))
        self.points4.setItemText(5, _translate("scoreBase", "5", None))
        self.points4.setItemText(6, _translate("scoreBase", "6", None))
        self.points4.setItemText(7, _translate("scoreBase", "7", None))
        self.points4.setItemText(8, _translate("scoreBase", "8", None))
        self.points4.setItemText(9, _translate("scoreBase", "9", None))
        self.points4.setItemText(10, _translate("scoreBase", "10", None))
        self.points4.setItemText(11, _translate("scoreBase", "11", None))
        self.points4.setItemText(12, _translate("scoreBase", "12", None))
        self.points4.setItemText(13, _translate("scoreBase", "13", None))
        self.points4.setItemText(14, _translate("scoreBase", "14", None))
        self.points4.setItemText(15, _translate("scoreBase", "15", None))
        self.label_12.setText(_translate("scoreBase", "Comments", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    scoreBase = QtGui.QDialog()
    ui = Ui_scoreBase()
    ui.setupUi(scoreBase)
    scoreBase.show()
    sys.exit(app.exec_())

